### ISSUE TITLE
GAE Datastore Eventual consistency section contains wrong information

### ISSUE THREAD

**Issue by anssih** [mdipierro/web2py-book#132]
In deployment recipes, under GAE Datastore the "Eventual consistency" section seems to be mostly wrong.

The first paragraph seems OK, but the second paragraph claims that web2py doesn't rely on "primary Datastore keys" and that the "id" field is just a regular field assigned by web2py. Reading the code that simply isn't the case, and hasn't been at least as far back as the git repository goes (2 years). The id is the actual DB-assigned id from the entity key.

Therefore the rest of the section (which explains the consequences with an example) is just wrong. The issue only exists if one tries to retrieve the newly added row by a non-id field.

I guess the example should be altered to retrieve the newly added row by a non-id field, or minimally completely removed.

**Comment by mdipierro** [comment]
removed the whole paragraph
