### ISSUE TITLE
mention this in the book about scheduler

### ISSUE THREAD

**Issue by mdipierro** [mdipierro/web2py-book#134]
https://groups.google.com/forum/#!topic/web2py/WIa1nSQJpe8

**Comment by BuhtigithuB** [comment]
@niphlod : Is this still accurate, or can we close this one?

**Comment by niphlod** [comment]
IMHO it has nothing to do with the scheduler at all

**Comment by BuhtigithuB** [comment]
So we can rejected it?

**Comment by niphlod** [comment]
again, IMHO it was not valid at all. @mdipierro who opened it should be the one ruling out if it's to close or not.

**Comment by BuhtigithuB** [comment]
One more closed...
