### ISSUE TITLE
errata

### ISSUE THREAD

**Issue by mdipierro** [mdipierro/web2py-book#165]
P.139 missing word:            "For example they will allow you <to> sync your app with..."
P.139 extra letter:            "..a Wizard that can help you create a new application<s>."
P.163 2 misspelling:            "For this reason<s> they are placed into a container calle<r> current, which is..."
P.165 jumbled words + missing word:    "nor one should use it <to> assign class attributes" should probably be: "nor should one use it to...."
P.177 double printing:            "If you are storing sessions on filesystems and ..." paragraph is repeated 2x
P.189 misspelling:            "provides a way to define pluralization rules for each language<s>, as well as..."
P.202 missing words/nonsensical:    "The version number of made part of the file url as in the previous example."
P.274 misspelling:            ".. it is possible that some table<s> are defined even if not needed."
P.286 superfluous word:            "If as_dict is set to True, <and> the results cursor returned by the DB driver will..."
P.296 wrong chapter ref:        "They will be explained in more detail in chapter <8>" Should be chapter 7 (SQLFORM, etc)
P.315 missing word:            "On relational databases they <are> all mapped into text fields..."
P.361 missing  argument name:        "<?> is a list oof INPUTs or TAGBUTTOONS..."
P.361 missing capitalization:        "<H>idden fields can be..."
P.361 superfluous word:            "So you have to <do> explicitly move hidden fields..."
P.381 missing word:            "Because the record is <never?> actually updated (only its previous state..."
P.405 missing letter:            "By default all the URI<s> generated by the grid..."
P.409 missing word:            "showbutton allowws <you> to turn off all buttons."
P.411 missing letter:            "There is a<n> extra argument constraints which is a..."
P.411 missing letter:            "There is a<n> extra argument linked_tables which is a..."
P.412 missing letter:            "that displays the table name and it need<s> both the singular and..."
P.412 missing letter:            "web2py normally guesses them but you can set the<m> explicitly:..."
P.501 superfluous letter:        "you can refer to the following <a> CSS-like equivalent..."

Also, the book would be tremendously improved through a more thorough (and corrected) index. Here's some things I have found missing/corrected:

BEAUTIFY, 162, 251
datetime, 69, 276, 317
FORM, 86, 240, 346(!!)
format, 92, 275
grids, 404
Also: Misspelling: IS_EQUEL_TO (sic)
jquery, chapter 11
jquery effects, 500
lambda, 62, 276
LOAD, 184, 515
linkto, 360, 367-9
multiple validators, 387
notnull, 275 (not p.274 as listed), 277
redirect, 85, 162, 184, 353
Rows objects, 291, 302, 325
SQLFORM, 101, 356, 370
SQLFORM.grid, 290, 404
SQLFORM.smartgrid, 296, 404
unique, 277 (not 274 as listed)
validators, 162, 385, 399
WWGET, 452, 535
XML, 235, 325-6, 464

**Comment by BuhtigithuB** [comment]
Is this one fix by the commit??

**Comment by timrichardson** [comment]
Yes almost entirely
