### ISSUE TITLE
link to URL helper broken

### ISSUE THREAD

**Issue by victor-rene** [mdipierro/web2py-book#166]
http://www.web2py.com/book/default/chapter/05#URL
leads to http://www.web2py.com/book/default/04#markmin_URL
which returns invalid function (default/04)
instead of http://www.web2py.com/books/default/chapter/29/04/the-core#URL

**Comment by BuhtigithuB** [comment]
Can be closed can't reproduce with the actual online book. All the refered links are working as they should... Mean you never get redirected over : http://www.web2py.com/book/default/04#markmin_URL

But over : http://web2py.com/books/default/chapter/29/04#markmin_URL which brings you on the proper content...
