### ISSUE TITLE
Self-closing tag generation with TAG helper

### ISSUE THREAD

**Issue by lightdot** [mdipierro/web2py-book#171]
Self-closing tags can be generated with the TAG helper. This is useful and could be added to the book (Custom helpers, TAG; 05.markmin around line 1214), along the lines of:

To generate a self-closing tag, the tag name must end with a "/".
```
{{=TAG['link/'](_href='http://web2py.com')}}
```
generates the following XML:
```
<link href="http://web2py.com"/>
```

**Comment by BuhtigithuB** [comment]
@timrichardson, can you reference the PR and can we close this one?
