### ISSUE TITLE
Second half of Chapter 9 is totally messed-up in the online version (pdf is fine)

### ISSUE THREAD

**Issue by kszys** [mdipierro/web2py-book#187]
Second half of Chapter 9 is totally messed-up in the online version (http://web2py.com/books/default/chapter/29/09/access-control). Everything is fine till "Renaming Auth Tables" section. The rest is pretty much unusable... This also includes the table of content. 

The PDF is fine on the other hand.

**Comment by BuhtigithuB** [comment]
Can this one be closed...
