### ISSUE TITLE
RESTful POST example problem

### ISSUE THREAD

**Issue by bmccoard** [mdipierro/web2py-book#194]
I copied the restful "more complex example" from the online book and spent hours trying to get it to work correctly.  Whenever I used curl to send a post it would return "errorid".   After debugging the code I realized the function was returning a row object instead of a dict.  The row object does not have the length attribute so the rocket server wouldn't return the correct data.  The fix is to simply have the POST routine return a dictionary:
```python
if table_name == 'person':
    return db.person.validate_and_insert(**vars)  
```
to
```python
if table_name == 'person':
    return dict(db.person.validate_and_insert(**vars))
```

This problem seems to also exist with most of the restful post examples.  Unless maybe it's an issue with web2py and the validate_and_insert function should return a dict instead of a row object.

**Comment by BuhtigithuB** [comment]
I think it can be closed
