### ISSUE TITLE
help command in web shell problem

### ISSUE THREAD

**Issue by andressantiago** [mdipierro/web2py-book#200]
when using the help command in the web shell it returns this:
![screen shot 2014-04-14 at 12 52 49 am](https://cloud.githubusercontent.com/assets/7192513/2691904/0f3e45ce-c391-11e3-9b9b-a252f27ccca4.png)
realized this after trying it from the Python Language chapter of the book.

**Comment by BuhtigithuB** [comment]
This can be closed, I just try with 2.14.3 and I can't reproduced, must had been fixed since that time... I think it was more a web2py issue than a book issue.

**Comment by mdipierro** [comment]
Thank you!
