### ISSUE TITLE
Return value of validate_and_insert wrong

### ISSUE THREAD

**Issue by stefan-scholl** [mdipierro/web2py-book#218]
http://web2py.com/books/default/chapter/29/06/the-database-abstraction-layer?search=validate_and_insert#validate_and_insert--validate_and_update

> errors can be found in ret.error. 

It's ret.errors

And the nature (type, use) of ret.errors isn't described.

**Comment by BuhtigithuB** [comment]
@stefan-scholl, ret.error were already fixed, but I am not sure what you mean in the las phrase... Would you more explanation about what is ret.errors??
