### ISSUE TITLE
Errata TheViews > HTML Helpers

### ISSUE THREAD

**Issue by xoguix** [mdipierro/web2py-book#228]
The 4th code block under HTML helpers reads like this:
<code>
{{=DIV(B(I("hello ", `"<world>"`))), _class="myclass")}}
</code>

The 3rd parenthesis after `<world>` is redundant and creates an error, the DIV parenthesis got already closed after <code>_class="myclass"</code>

**Comment by BuhtigithuB** [comment]
Can be closed : 
http://www.web2py.com/books/default/chapter/29/05/the-views?search=helper#HTML-helpers
Seems fine :

> {{=DIV(B(I("hello ", "<world>")), _class="myclass")}}
