### ISSUE TITLE
python 2.5 has been deprecated on GAE 

### ISSUE THREAD

**Issue by ilvalle** [mdipierro/web2py-book#252]
https://cloud.google.com/appengine/docs/python/python25/diff27

**Comment by BuhtigithuB** [comment]
Python 2.5 seems all over the place in the book... I think we are not supporting it anymore, no?

Ok, 3 places: 
http://www.web2py.com/books/default/chapter/29/01/introduction?search=python+2.5

http://www.web2py.com/books/default/chapter/29/02/the-python-language?search=python+2.5

http://www.web2py.com/books/default/chapter/29/13/deployment-recipes?search=python+2.5

:D

**Comment by mdipierro** [comment]
No. No more.
