### ISSUE TITLE
Small error in chapter 4

### ISSUE THREAD

**Issue by ailnlv** [mdipierro/web2py-book#257]
In the 'Homemade task queues' section, the book claims that by running 

    python web2py.py -S app -M -R applications/app/private/myscript.py -A a b c

you get the command line arguments 'a', 'b' and 'c':

    sys.args=['a','b','c']

It should say instead

    sys.argv=['applications/app/private/myscript.py','a','b','c']

There is no `args` in `sys`.

**Comment by timrichardson** [comment]
fix in PR
