### ISSUE TITLE
"Next" and "Previous" Buttons 

### ISSUE THREAD

**Issue by shubhamoli** [mdipierro/web2py-book#291]
I want to give a friendly suggestion to include "Next" as well as "previous" buttons (online version) for moving back and forth while reading the chapters, as it is very non-intuitive to scroll back while you are reading something and you have to change chapters for some references.

Hope you will see in this regard.

**Comment by BuhtigithuB** [comment]
Don't understand, you can use browser button for that no? or CTRL + left/right arrow...

**Comment by mdipierro** [comment]
I do not understand. I do not see [next] and [previous] buttons.

**Comment by BuhtigithuB** [comment]
I think this one could be solve by having table of content moving up/down
automatically as the page scroll, like that you don't need these buttons
(as the don't make any sens to me anyway to be allowed to change of
chapiter when at a buttom of a page). But not having to go back on top of
the page to se the table of content could be a great improvement for the
navigation exprience of the book...

I try 1 or 2 times to implement that, but failed with the time I allowed me
to do it...

We may let this one close and open another one for a moving table of
content... What do you think?

Richard
