### ISSUE TITLE
Incorrect POST return value in Restful Web Services example

### ISSUE THREAD

**Issue by abastardi** [mdipierro/web2py-book#297]
In the Restful Web Services section, there is a repeated example that returns a .validate_and_insert() result in response to a POST request. The example should return a dictionary (or JSON) rather than the Row object generated by .validate_and_insert().

For details, see https://groups.google.com/d/msg/web2py/TDPiz6-DMkc/eaNrGoozCgAJ.

**Comment by BuhtigithuB** [comment]
Duplicate #194
