### ISSUE TITLE
Answer from validate_and_insert (webservices)

### ISSUE THREAD

**Issue by jaimesemp** [mdipierro/web2py-book#307]
Hi,

I have found on the webservices chapter of the book, we are suggested to write a simple post service using this:

```

@request.restful()
def api():
    response.view = 'generic.json'
    def POST(**fields):
        return db.person.validate_and_insert(**fields)
    return locals()

```

If I use this code directly my client (im using postman extesion on chrome) just reply :  errorsid

I need to wrap the answer into a response.json like this:

```

 return response.json(db.person.validate_and_insert(**fields))

```

I am not sure if this would be a 'bug' of web2py or of the book (or maybe this behaviour is the expected and the user/programmer need to know that he need to treat the answer like a json... but just in case...)

**Comment by mdipierro** [comment]
this should be fixed now in the code (the book was correct).
