### ISSUE TITLE
[english book] Duplicate section in deployment recipes

### ISSUE THREAD

**Issue by gitoni** [mdipierro/web2py-book#310]
http://web2py.com/books/default/chapter/29/13/deployment-recipes#Deployment-recipes--Infrastructure
seems to be the same as
http://web2py.com/books/default/chapter/29/13/deployment-recipes#Deployment-recipes-

except some mysterious

> B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A

at the end of the section

**Comment by gitoni** [comment]
Related pull request:
https://github.com/mdipierro/web2py-book/pull/311

**Comment by mdipierro** [comment]
thanks
