### ISSUE TITLE
NameError in default meny.py

### ISSUE THREAD

**Issue by m8ram** [mdipierro/web2py-book#318]
Hi,

Opening the appadmin page for the images example from the reference manual fails with a NameError caused by the menu.py that is created by default:
```
<type 'exceptions.NameError'> name 'myconf' is not defined
Version
web2py™ 	Version 2.14.3-stable+timestamp.2016.03.26.23.02.02
Python 	Python 2.7.10: /usr/bin/python (prefix: /usr)
Traceback
Traceback (most recent call last):
  File "/home/m8ram/workspace/web2py/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/home/m8ram/workspace/web2py/applications/images/models/menu.py", line 15, in <module>
    response.meta.author = myconf.get('app.author')
NameError: name 'myconf' is not defined
```

Removing models/menu.py appears to resolve (or at least work around) the issue.

What is happening here?
How can I avoid this and should this be added to the manual?

Thanks in advance

Bram

**Comment by BuhtigithuB** [comment]
Hello,
Is this a web2py error? if so, you should post this issue here : 
https://github.com/web2py/web2py/issues

**Comment by mdipierro** [comment]
The issue is that the db.py does not define myconf. The book should explain myconf.

**Comment by liusuihui** [comment]
I have Removed models/menu.py, and then the problem appears to resolve.
Remeber delete the models/menu.py

**Comment by BuhtigithuB** [comment]
Don't think it a good workaround... Instead you could change the line that
refer to myconf if you are not using it...

Richard
