### ISSUE TITLE
Deprecated translation in Russian

### ISSUE THREAD

**Issue by nmarusov** [mdipierro/web2py-book#334]
http://web2py.com/books/default/chapter/39 points to the deprecated (unfinished?) translation into Russian. Also it yields the issue https://github.com/mdipierro/web2py-book/issues/332
Book deployed locally from git has two translations in menu: Chapter 39 with the bug and Chapter 43 that's OK (http://127.0.0.1:8000/book/default/chapter/43).
Actions:
1. Leave only one translation in Russian.
2. Update the book in production at http://web2py.com/books

**Comment by mdipierro** [comment]
It is a caching issue. I restarted the server and should be ok now. Please check it. Feel free to email me personally if you nothing something else is still wrong.
