### ISSUE TITLE
Observations on the 5th English edition

### ISSUE THREAD

**Issue by spametki** [mdipierro/web2py-book#54]
These may or not be corrections, therefore I cannot make a pull request out of them:

1) Components and plugins (Chapter 12):

First, the book says:
"... The files that compose a plugin are not treated by web2py any differently than other files except that admin understands from their names that they are meant to be distributed together, and it displays them in a separate page:.."

But, then, it says

"... Yet as a matter of fact, by the definition above, these plugins are more general than those recognized as such by **admin**. ..."

It's not clear to me what type of plugin is supposed to be more general, a web2py plugin or a common plugin

2) The abbreviated notation for addresses of the wiki code examples are not escaped AFAIK. For me, they should have this syntax to render properly:

``\@////contactenos``:code

That is the syntax I used for the spanish translation

3) There seems to be a confuse usage of uppercase or lowercase for markmin and MARKMIN. I think the proper notation is:

- markmin for refering to the markup language.
- ``MARKMIN`` or MARKMIN for refering to the core helper
- ''markmin'' or **markmin** for emphasizing the markup language.

4) Chapter 9: accessible_query is marked as incompatible with GAE, but I think that the book should note that it is (I suppose) supported by the GAE SQL adapter.

5) Several lines in code examples of the english version have one "\" for splitting lines, while there's need to use two "\\\\" for proper render. I did not apply this change since I'm not sure it is the correct syntax.

6) Chapter 13:
This:
"... Sessions are automatically forgotten is unchanged. ..."

Should not be changed with this?
"... Sessions are automatically forgotten if unchanged. ..."

7) Chapter 6:

Routes of classes such as DAL, Rows, ... include .sql., which is an old notation. Why not use the new syntax, such as gluon.dal.Class?

8) Chapter 0:
It says "You are free to use web2py" (or similar). I think it would be convenient to note that web2py is open source, not freeware, and also maybe a link to the licence section of chapter 01. "You are free to use ..." can lead to undesirable misunderstandings.

EDIT:

9) Chapter 7:

line 2537
"... The grid and smartgrid gadgets are here to stay but they are marked experimental ..."

A previous blockquote near line 2287 says that since 2.0 grid and smartgrid are not experimental anymore. Both sentences are somewhat contradictory.

10) Chapter 6:
delete_record (although it is self-explained as some will hasten to observe) is only mentioned as unavailable option when retrieving cached Row objects. The feature is not listed anywere else. 

11) Chapter 4:

"... private  files are accessed by the controllers but not directly by the developer. ..."

Currently, the admin app allows accessing the private folder the same way as with static, models, etc. The restriction described in the book does not apply for the current version. IIRC, other sections of the book mention the private folder as invisible to the developer.

12) Chapter 4 (and maybe others as well):

There are code comments with "# ..." or "#...". It's not clear if they should have actual comments or be removed.

**Comment by BuhtigithuB** [comment]
Is there any still relevant things here?? I didn't read, sorry...

**Comment by mdipierro** [comment]
i fixed most of the issues.
