### ISSUE TITLE
The recipe for retrieving tweets is broken

### ISSUE THREAD

**Issue by spametki** [mdipierro/web2py-book#90]
The new twitter api does not support simple http requests, so the current recipe in the book will not work. In fact, the tweets widget in the admin app had to be replaced with a js timeline for the same reason.

Now, api requests from apps need OAuth authentication, provide app special keys, etc.

https://dev.twitter.com/docs/auth

**Comment by BuhtigithuB** [comment]
Should we remove this recipe ?

**Comment by mdipierro** [comment]
removed.
